/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    CarRegisterForm: typeof import('./src/components/CarRegisterForm.vue')['default']
    CarRentalForm: typeof import('./src/components/CarRentalForm.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    PagesBar: typeof import('./src/components/PagesBar.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserRegisterForm: typeof import('./src/components/UserRegisterForm.vue')['default']
  }
}
